# Visit https://goreleaser.com for documentation on how to customize this
# behavior.
before:
  hooks:
    - go mod tidy
builds:
- env:
    - CGO_ENABLED=0
  mod_timestamp: '{{ .CommitTimestamp }}'
  flags:
    - -trimpath
  ldflags:
      - -X github.com/Mirantis/launchpad/version.Environment=development
      - -X github.com/Mirantis/launchpad/version.GitCommit={{ .FullCommit }}
      - -X github.com/Mirantis/launchpad/version.Version={{ .Version }}
  goos:
    - freebsd
    - windows
    - linux
    - darwin
  goarch:
    - amd64
    - arm
    - arm64
  binary: '{{ .ProjectName }}_v{{ .Version }}'
archives:
- format: zip
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256
release:
  # If you want to manually examine the release before its live, uncomment this line:
  # draft: true
changelog:
  skip: true