apiVersion: launchpad.mirantis.com/v2.1
kind: mke
metadata:
  name: lp2-leg
spec:
  components:
    hosts:
      ACon0:
        handler: mock
        roles:
        - manager
      AWrk0:
        handler: mock
        roles:
        - worker
      AWrk1:
        handler: mock
        roles:
        - worker
    mcr:
      version: 23.0.7
      repoURL: https://repos.mirantis.com
      installURLLinux: https://get.mirantis.com/
      installURLWindows: https://get.mirantis.com/install.ps1
      channel: stable
      prune: true
    mke3:
      version: 3.7.3
      imageRepo: docker.io/mirantis
      adminUsername: admin
      installFlags:
      - "--default-node-orchestrator=kubernetes"
      - "--nodeport-range=32768-35535"
      upgradeFlags:
      - "--force-recent-backup"
      - "--force-minimums"
    msr2:
      version: 2.9.30
